# Generated by Django 5.2.2 on 2025-06-09 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_fornecedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('unidade', models.CharField(choices=[('ml', 'Mililitro'), ('lt', 'Litro'), ('g', 'Grama'), ('kg', 'Quilograma'), ('m3', 'Metro cúbico')], max_length=10)),
                ('deposito_padrao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.deposito')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.fornecedor')),
            ],
        ),
    ]
